### ISSUE TITLE
Releases create vsix file

### ISSUE THREAD

**Issue by Nosferican** [chang196700/newline#1]
Would be great if the releases publish the `vsix` to make it available with non-Microsoft products.

**Comment by chang196700** [comment]
I don't know much about GitHub's command to commit the release file, so I need to manually compile and submit the release.

**Comment by Nosferican** [comment]
@davidanthoff could you share how to make it such that the GitHub release creates the `vsix` assets?

**Comment by davidanthoff** [comment]
Take a look at https://github.com/julia-vscode/julia-vscode/blob/master/azure-pipelines.yml, that has all the packaging automation we use.

**Comment by chang196700** [comment]
Thanks for the sample, I have updated the file and it can submit the release file automatically.
